moving group testing trigger to rhods-ci bot

diff --git a/konflux-tekton-tasks/trigger-group-testing/0.1/trigger-group-testing.yaml b/konflux-tekton-tasks/trigger-group-testing/0.1/trigger-group-testing.yaml
--- a/konflux-tekton-tasks/trigger-group-testing/0.1/trigger-group-testing.yaml
+++ b/konflux-tekton-tasks/trigger-group-testing/0.1/trigger-group-testing.yaml
@@ -30,6 +30,11 @@ spec:
       valueFrom:
         fieldRef:
           fieldPath: metadata.annotations['pipelinesascode.tekton.dev/original-prname']
+    - name: GITHUB_TOKEN
+      valueFrom:
+        secretKeyRef:
+          name: odh-github-secret
+          key: commenter-token
     script: |
       #!/bin/bash
       set -e
@@ -42,9 +47,14 @@ spec:
       if [ "${WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND}" = "true" ]; then
         echo "configuring gh cli"
         ls -la "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}"
-        GITHUB_TOKEN=$(cat "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}/git-provider-token")
+        # GITHUB_TOKEN=$(cat "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}/git-provider-token")
       fi
       
+      if [ -z "$GITHUB_TOKEN" ]; then
+          echo "Error: GITHUB_TOKEN env is not set."
+          exit 1
+      fi
+    
       # GitHub API endpoints
       API_BASE="https://api.github.com"
       PR_URL="$API_BASE/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER"
